apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: golang-accelerator
  annotations:
    github.com/project-slug: coyte/golang-accelerator
spec:
  type: other
  lifecycle: unknown
  owner: dutch-team
