apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: golang-accelerator
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: golang-accelerator
    apps.tanzu.vmware.com/has-tests: "true"
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      url: https://github.com/TanzuDK/golang-accelerator.git
      ref:
        branch: main
